### PR TITLE
Removed more upscaled stuff from the main branch

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
In addition, I have manually rescaled several assets in Phase 3, which were previously scaled incorrectly.

**Comment by ghost** [comment]
Files in 3.5 that were scaled improperly are now also fixed. (By scaled improperly, I meant those that had weird alaising artifacts from scaling) As a sidenote, I noticed that the way some objects are sized, are different from the ones in the game. For my resizings, i matched the textures to the same aspect ratio of those textures. There are textures that are currently fine in both Phase 3, and 3.5 that have different scaling than what was in the game originally. If panda scale's those automatically to the correct size, cool. If it don't, someone should compare and fix textures that don't currently match game dimensions. (By game dimensions, I don't mean the EXACT resolution, just aspect ratio.)

**Comment by ghost** [comment]
Section C of the readme was updated at some point by me, but was too complicated, and inadvertently caused more damage, than it did help. Section C is now in a state from before I messed with. I still feel it could be elaborated on, or worked on, in some form, but for now, this will do.

**Review by loonaticx — APPROVED** [review]

**Comment by loonaticx** [comment]
Thanks!

**Pull request merged**
