### PR TITLE
Added HD Eyes

### PR DESCRIPTION
**Pull request by ghost**
Noticed the eye textures were a bit low res, still. Here's HD versions, upscaling using various ESRGAN models. Should looks miles better than what is currently in. As usual, my source files are in the !SOURCE FILES folder, if needed.

### CODE REVIEW

**Comment by ghost** [comment]
Also, thanks to the efforts of weirdwacko, the Cogs that needed palletization, are now palletized!

**Comment by loonaticx** [comment]
Where are the project files for the suit heads/palettized graphics? Refer to rule a on the guidelines

**Review by loonaticx — CHANGES_REQUESTED** [review]
Where are the project files for the suit heads/palettized graphics? Refer to rule a on the guidelines

**Comment by ghost** [comment]
The eyes, suits, and cog heads, have no project files. The files for the Suit palletized files are from weirdwacko, and they would need to submit them, themselves, in terms of project files.

**Comment by weirdwacko** [comment]
I'd suggest you remove them, since I am currently submitting them in my own pull request at the moment.

**Comment by weirdwacko** [comment]
"Them" referring to my palletes.

**Comment by ghost** [comment]
Done

**Comment by ghost** [comment]
The source files for the palletes are from a pull wacko has done. I have removed the palletes from this pull, as they are old, and better ones were added in by wacko in another pull, as well.

**Comment by loonaticx** [comment]
I appreciate your contributions. I know you are aiming to create crispier quality versions for some of these textures using neural network-based upscaling algorithms. The only concern I have of this is that- I know they are ultimately much higher resolution than pandora- but I would prefer for them not to be associated with the _original_ textures we're working with. I would rather have these edits on a different branch where people can have an option whether to use completely natural assets or AI-based upscaling enhancements. 

That being said, I created a new branch labeled AI-Enhancements designated for these assets. Please make a new pull request towards this branch and use it from now on with artificial upscaling.

 At the end of the day when this project gets close to completion, I will provide a download link to this version of the pack alongside others, such as a TTR compatible version. I don't want to sound super-exclusive about this as I very do support your contributions, however the aim for master is to keep it as original as possible.

**Pull request closed without merging**
